version: '3'
services:
  web:
    build: './web'
    ports:
      - "3000:3000"

  feedback:
    build: './feedback'
    ports:
      - "3001:3000"
    depends_on: 
      - db  

  db:
    image: mysql:5.7.21
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - feedback
  