version: '3'
services:
  # web:
  #   build: './web'
  #   ports:
  #     - "3000:3000"

  feedback:
    build: './feedback'
    ports:
      - "3001:3000"
    depends_on: 
      - db  
    environment:
      - NODE_ENV=development

  db:
    image: mysql:5.7.21
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=dev

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./web/public:/srv/www/static
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
      # - web
      # - feedback
  